### ISSUE TITLE
Add quantity expectations per ingest

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#682]
For each ingest, we should raise an error if the totals are outside of some add some min and max expected bounds

These bounds could be set in the ingests.yaml, and the code to check them could live in the ingest code. We could also include some post-merge stats, such as at least 100,000 gene to phenotype edges, but less than 1,000,000, etc.

Thanks to @matentzn for the suggestion!

**Comment by monicacecilia** [comment]
Not a priority. But, @amc-corey-cox, for a "coffee break" length of time, maybe... could I kindly ask you to please assess the feasibility and/or current status of this? :eyes: 👆

**Comment by amc-corey-cox** [comment]
Hmm, this seems completely reasonable... I think we could use current Monarch KG release as a baseline and just say; nothing should differ by more than say 5% lower... We should probably also flag anything greater than ~25% higher, too. This seems feasible for next release to me.

@kevinschaper where would you like this to live?

**Comment by kevinschaper** [comment]
@amc-corey-cox At one point I thought about putting count expectations into [ingests.yaml](https://github.com/monarch-initiative/monarch-ingest/blob/main/src/monarch_ingest/ingests.yaml), but maybe it makes more sense to go after the ["Monarch rules"](https://qc.monarchinitiative.org/rules/) approach instead, so that we can make more specific assertions?  The down side could be a lot of boilerplate query code. 

Inspired by the [data tables](https://spockframework.org/spock/docs/2.3/data_driven_testing.html#data-tables) in Spock test framework, we could encode the rules in terms of a count, an operator and a list of constraints? 

```
rules:
  - collection: nodes   # table? 
    count: 30000
    operator: gt  # I assume an enumeration of operators as strings makes the most sense?
    field_constraints:  # or maybe just constraints? 
      category: "biolink:Gene"
      taxon: "NCBITaxon:9606"
```

This way we would be able to apply the rules to any one of our data artifacts or all of them. A linkml schema for this format obviously makes sense too.
