### ISSUE TITLE
HPOA ingest mis-maps some evidence types

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-app#827]
PCS, ICE getting mapped incorrectly

I think this dates from pre-2016

ECO has had the right codes for a while

https://github.com/evidenceontology/evidenceontology/issues/106

eg

```yaml
id: ECO:0006017
name: author statement supported from referenced clinical study used in manual assertion
def: "A type of author statement supported from referenced clinical study that is used in a manual assertion." []
comment: Created and used by the Human Phenotype Ontology (HPO) Annotations group. Here it is used when evidence for an HPO annotation is information extracted from articles in the medical literature.
synonym: "PCS" EXACT [HPO:PCS]
synonym: "published clinical study evidence" BROAD []
is_a: ECO:0000304 {is_inferred="true"} ! author statement supported by traceable reference used in manual assertion
is_a: ECO:0006016 ! author statement supported from referenced clinical study
intersection_of: ECO:0006016 ! author statement supported from referenced clinical study
intersection_of: used_in ECO:0000218 ! manual assertion
property_value: seeAlso http://human-phenotype-ontology.github.io/documentation.html#annot xsd:string
created_by: rctauber
creation_date: 2016-11-30T09:44:47Z

```

**Comment by kevinschaper** [comment]
This has been corrected in the current ingest (`monarch-phenotype-profile-ingest`, the kozahub successor to the HPOA ingest). The evidence-code → ECO mapping now uses the post-2016 codes, defined in [`src/phenotype_ingest_utils.py`](https://github.com/monarch-initiative/monarch-phenotype-profile-ingest/blob/main/src/phenotype_ingest_utils.py):

| HPOA `evidence` | ECO class | ECO label (exact synonym) |
|---|---|---|
| `IEA` | `ECO:0000501` | evidence used in automatic assertion (IEA) |
| `PCS` | `ECO:0006017` | author statement supported from referenced clinical study, manual assertion (PCS) |
| `TAS` | `ECO:0000304` | author statement supported by traceable reference, manual assertion (TAS) |
| `ICE` | `ECO:0006019` | inference based on individual clinical experience, manual assertion (ICE) |

These codes match ECO's own exact `HPO:` synonyms, i.e. the codes called for in evidenceontology/evidenceontology#106.

This only affects the transforms that read `phenotype.hpoa` — `disease_to_phenotype` and `disease_mode_of_inheritance`. `gene_to_disease` reads `genes_to_disease.txt`, which carries no 3-letter evidence codes, so it was never affected.

### Example (disease_to_phenotype)

Input row from `phenotype.hpoa`:

```
database_id: OMIM:615654
hpo_id:      HP:0007663
qualifier:
reference:   PMID:32337552
evidence:    PCS
aspect:      P
```

Resulting `DiseaseToPhenotypicFeatureAssociation`:

```yaml
subject: OMIM:615654
predicate: biolink:has_phenotype
object: HP:0007663
has_evidence:
  - ECO:0006017        # PCS, correctly mapped
publications:
  - PMID:32337552
primary_knowledge_source: infores:omim
aggregator_knowledge_source:
  - infores:monarchinitiative
  - infores:hpo-annotations
```

`ICE` likewise resolves to `ECO:0006019` rather than a stale/generic code. Closing as fixed.
