### ISSUE TITLE
Turn kg-registry into the OBO for KGs

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#888]
We need to update https://github.com/Knowledge-Graph-Hub/kg-registry so that we can better track knowledge graphs and modular graph components. 

We should stick with the registry.yaml as the foundation, but expand with a LinkML schema that will allow for validation and documentation of the fields. 

We need to add some kind of a type/category field that captures the distinction between an aggregated graph, a single source graph and a graph component (just edges, just nodes). We could also consider splitting this out into separate boolean fields. (Is it aggregated? is it a complete graph? )

There should be a products section, like OBO, we might want to use an enum for product types, but allow some kind of "other" so that we're flexible. The motive there is that some types might be especially nice for doing some computational work to produce a dashboard, or a giant merge of all kgx archives, etc. 

```
  preferredPrefix: GO
  products:
  - description: The main ontology in OWL. This is self contained and does not have
      connections to other OBO ontologies
    id: go.owl
    ontology_purl: http://purl.obolibrary.org/obo/go.owl
    page: http://geneontology.org/page/download-ontology
    title: GO (OWL edition)
  - description: Equivalent to go.owl, in obo format
    id: go.obo
    ontology_purl: http://purl.obolibrary.org/obo/go.obo
    page: http://geneontology.org/page/download-ontology
    title: GO (OBO Format edition)
  - description: Equivalent to go.owl, in obograph json format
    id: go.json
    ontology_purl: http://purl.obolibrary.org/obo/go.json
    page: https://github.com/geneontology/obographs/
    title: GO (JSON edition)
``` 

There should be an optional infores ID field for the graph itself.  `homepage`, `description`, other good ideas borrowed from https://obofoundry.org/registry/ontologies.yml
